module DeckName
  Known = [
    ["LiLgLn-TnGmGw-gHLLn6", "アルセウスVSTAR"],
    ["8x8x48-QzM65x-cxxGKx", "アルセウスVSTAR"], # うらこうさく
    ["gngLiL-WKQgyP-gLnLNL", "アルセウスVSTAR"], # うらこうさく
    ["yMXyUX-Zl2HpI-XySpSM", "アローラロコン そらをとぶピカチュウ"],
    ["NNLHQL-3Saux2-nLinnL", "オリジンパルキアVSTAR"],
    ["xGDcY8-9Atco7-xDx8a8", "オリジンパルキアVSTAR"],
    ["6gLnig-A7WC7T-QgLngn", "オリジンパルキアVSTAR"],
    ["MyypyX-yR2Rbd-2UMSMM", "キュレム パルキア"],
    ["kFVkFF-YMbSeC-kkFFkV", "キュレム パルキア"],
    ["kkk1F5-gGq15i-kk1VFb", "キュレム アローラロコン"],
    ["kkFkk1-zfhk8c-VbkVVk", "コケコ そらをとぶピカチュウ"],
    ["2pyyMy-Ln3Pa8-yyMMyS", "コケコ そらをとぶピカチュウ"],
    ["MMRMM2-UrIGQG-p3XMyy", "そらをとぶピカチュウ アルセウス"],
    ["2MSyMy-HbjAnB-MXyyXp", "そらをとぶピカチュウ アルセウス"],
    ["Lg6Hnn-cc7Kg9-nnLnnL", "そらをとぶピカチュウ アルセウス"],
    ["6nngnL-yaDCqB-gngnLL", "そらをとぶピカチュウ アルセウス"],
    ["XXMp3y-RZNFZT-pyXy2y", "ギラティナ アルセウス"],
    ["cc8x8c-QVf0C6-8x88c8", "ギラティナ アルセウス"],
    ["dV5kfV-dCe4mL-VdkV51", "ジュラルドン アルセウス"],
    ["Vv1vkV-xfzQQr-kVkFkV", "ジュラルドン アルセウス"],
    ["pMpyyp-y6qr3X-yMypUy", "ジュラルドン アルセウス"],
    ["VfkkV5-QwzM1B-Vkbv1V", "ジュラルドン アルセウス"],
    ["bkVkkk-L1Gt6e-fFkFfb", "ジュラルドン アルセウス"],
    ["LnnnLL-xxFlSc-n6LinH", "ジュラルドン アルセウス"],
    ["dVVkkV-IBRjwg-VVkVbk", "ジュラルドン アルセウス"],
    ["VkkVk5-vbutvx-kVFwkf", "ジュラルドン アルセウス"],
    ["48YJ8c-3EKPdw-DxcKD8", "ジュラルドン アルセウス"], # かがやくムゲンダイナ
    ["yyMyMM-Z5JEyZ-M2ypUX", "ゾロアーク"],
    ["yyyM2M-Zgfdkb-SME22M", "ゾロアーク"], #ヒスイ ゾロアーク
    ["UyyXME-JAghpd-yypyy2", "ゾロアーク"], #ヒスイ ウィンディ
    ["pMpyE2-N3FZ44-MypMyM", "ゾロアーク"],
    ["VkFvkw-TASUx9-VVVkVV", "ゾロアークVSTAR"],
    ["LL69gn-trUMzn-nL9gnn", "ゾロアークVSTAR"],
    ["QnHNnn-0rIYSO-nLHLnN", "ヒスイヌメルゴン アローラロコン アルセウス"],
    ["kFkkFV-fJIhh2-kf5k1V", "マタドガス ムゲンダイナVMAX"],
    ["nLnggg-bzZ5J7-HgLnHH", "ミュウVMAX"],
    ["niLLPL-tyJQe1-gnnLQQ", "ミュウVMAX"],
    ["D8848J-NRLceF-xc448x", "ミュウVMAX"],
    ["DxD8c8-Rh4mtx-xJxcc4", "ミュウVMAX"],
    ["Lnngnn-5jj8Z9-NNn6PN", "ミュウVMAX"],
    ["FkkFvk-UK4x2y-VVFFkw", "ミュウツーV-UNION"],
    ["iLgnni-5W7MFN-Q69ngn", "ミュウツーV-UNION"],
    ["L9LLnN-UOVCCT-Lgn6gL", "ムゲンダイナVMAX"],
    ["HNLNnn-oKw2Uo-nnLgnn", "ムゲンダイナVMAX"],
    ["Vv5fVk-NZxydp-FVVkkv", "ムゲンダイナVMAX"],
    ["yM2yyX-IlINvd-yMyyyS", "メタモンLO"],
    ["G88Yx8-Mu2OHC-c48Dxx", "メタモンLO"],
    ["x8cx8x-7lAAIA-88KG84", "ルギアVSTAR"],
    ["fkkfk5-GkvwDU-vVkkV1", "ハピナスV"],
    ["yy2M2p-L5KX6A-ySSpMX", "ルギア そらをとぶピカチュウ"],
    ["GDDa8c-05dv00-8x8Gxc", "ルギア そらをとぶピカチュウ"],
    ["c8xxYc-ldylN3-c88888", "ルナトーン ソルロック"],
    ["F5VFbV-Wrub8f-kk5FVk", "レジエレキVMAX クワガノン"],
    ["yMM2yM-iKTV6Y-pMUpp3", "レジエレキVMAX クワガノン"],
    ["yMMUyM-K1LaWB-yyypXy", "レジエレキVMAX クワガノン"],
    ["yMpypU-VKlvc8-pyyM2M", "レジギガス"],
    ["gnQLHg-1AaruO-nnngnn", "レジギガス"],
    ["4884DJ-3zEddf-xD8xcK", "レジドラゴVSTAR"],
    ["J8a8JD-pXJV37-Y8cxx8", "ロスト かがやくムゲンダイナ"], 
    ["8Yaxcx-FSlPpQ-8x8xcx", "ロスト ギラティナVSTAR"],
    ["xc8aGx-8tEipa-JD8888", "ロスト ギラティナVSTAR"],
    ["M3yM2y-15uChl-yyySSX", "ロスト ゼラオラ"],
    ["8K8xxx-w7qMXf-8x88x8", "ロスト"],
    ["n9ggng-2Y4KdR-N6LnLn", "ロスト"],
    ["8xxx8Y-r1RHlR-4cG8JY", "ロスト"],
    ["MMyMXy-gxnyak-yMXyM3", "ロスト"],
    ["Jc84cJ-QgVka6-DD8x8K", "ロスト"],
    ["VkVFFf-BIdt7p-kk5V5F", "ロスト"],
    ["fVfFkk-KWWo4B-VkvVkF", "ロスト"], #レシラム
    ["gNNgLn-iz2ItL-QngnnL", "ロスト"],
    ["nnggnQ-BQoY6p-LgLg66", "ロスト"], 
    ["pSMMSy-eeiHQK-pyypyS", "ロスト"],
    ["FkwVwk-CpUB9b-VFkVfk", "ロトムVSTAR"],

    ["cY8c8c-qmqT4I-cD4DD8", "ロスト"],
    ["22MSEp-umOtxd-ppyyXy", "ミライドンex レジエレキVMAX"],
    ["Nngnnn-4q2tPJ-gNQQHn", "ミュウVMAX"],
    ["F1FffF-bvgoR3-FkvVkk", "ルギア いちげき"],
    ["dVFkvF-mfttTR-fVfk1F", "ルギア いちげき"],
    ["Y8YGD8-SY1b3l-cGxJc8", "オリジンパルキア はくば"],
    ["4888cD-3jyliZ-884acx", "サーナイトex"],
    ["84GGcx-h5uSt7-cDGDx8", "サーナイトex"],
    ["dkdVkV-vCUk0x-VFF5f5", "サーナイトex"],
    ["PN6NLH-fKoDoH-gnHHgn", "サーナイトex"],
    ["Dc84D8-ikWxuZ-88cYcx", "ゾロアークVSTAR"],
    ["N9NggH-fzceQT-nngQQn", "オリジンパルキア カイオーガ"],
    ["FF1FkF-Wl3TRm-kFwkkf", "アルセウス ギラティナ"],
    ["ypMyXM-QfXNv2-UpyMpX", "アルセウス ジュラルドン"],
    ["kkfV1F-OhPxSY-VkFFFd", "アルセウス はくば"],
    ["nngNgg-nB1o0P-nNNgnN", "アルセウス こくば"],
    ["F5kf5V-hUB4oZ-Vk1fkf", "アルセウス グレンアルマ"],
    ["HgngHn-UxIZEy-ngNQng", "ダークライVSTAR"],
    ["pyMSSp-pupzkp-ypySpX", "れんげきウーラオス"],
    ["ngnnNL-1Cme38-NNN6gL", "ルギア"],
    ["nnQgnn-rafcqM-QQnN99", "ミライドンex ピカチュウ"],
    ["LNnP69-KKtpJZ-nggN6n", "ルギア れんげき"],
    ["KDDxcx-cGFwc1-Dcc8aD", "オリジンディアルガ"],
    ["pMSMSX-Z0GkdT-yyM2py", "パオジアンex"],
    ["ngNH6N-OnPW8h-nLQgnQ", "アルセウス ヒスイヌメルゴン"],
    ["Xy23Up-viOHUm-3MRXpS", "だんけつのつばさ"],
    ["pSyXMp-kmmeE6-MUXS2y", "アルセウス そらをとぶピカチュウ"],
    ["c8JYcD-dLM4r0-DD48cc", "パオジアンex"],
    ["5dV511-NhPy8P-FFkbFf", "ディンルーex"],
    ["6HgHQg-cucRYO-NNLngN", "ミライドンex"],
    ["4cccGD-uJ16yR-c8Gx8K", "ロスト"],
    ["KDJ88c-83oUAa-cD88YK", "リザードンex"],
    ["bwfF5k-UFGfLR-FfdbkF", "アルセウス ロコン"],
    ["n6gQnQ-KP5uzZ-nQgNLn", "ミライドンex"],
    ["cD88aK-ibcJTL-cDDDKc", "パオジアンex"],
    ["pXMSXp-xOjxhY-RMyyyS", "サーフゴー"],
    ["pppypy-iA8DRz-XMyppX", "アルセウス ジュラルドン"],
    ["vbwvfV-tmNgo0-VwFkVf", "ゾロアーク"],
    ["MUyy3p-7eTadV-XMUpMy", "トドロクツキex"],
    ["fkFwkV-RyHGgA-Fk1kf5", "テツノブジンex"],
    ["xccGK8-R0WDa2-8J8Dxx", "サーフゴー"],
    ["NLgLNN-SJ4ceT-QnL9L6", "リザードンex"],
    ["fFVfVV-8zdzw1-5v1Vkk", "テツノブジンex"],
    ["XXyypM-duW4Zf-XRyMMy", "ガケガニ"],
    ["8884xx-hunmYi-xc8cxD", "カビゴンLO"],
    ["xc8Ycc-5zoJTq-G848aJ", "リザードンex"],
    ["NgnHHg-xMJ4Xb-n9ngL9", "パオジアンex"],
    ["Sy22yX-EXerT1-EMppSM", "トドロクツキex"],
    ["SyS2py-uCkGFJ-MyEypE", "サーフゴー"],
    ["VF5wkd-jH7XAp-F5k5kv", "イダイナキバLO"],
    ["yXEUp2-cFY4yc-MEyEpy", "ロスト"],
    ["FFVFk5-WhTouh-d5vVkk", "アルセウス ギラティナ"],
    ["MSyyyX-uV3xfU-R2ySpp", "カビゴン"],
    ["8xx4DY-QZq5UL-cc8x48", "モルフォン"],
    ["Y8c84D-34JMKF-D8Kxcc", "チラチーノ"],
    ["5F1kvF-22Fauy-VVVkvF", "サーナイトex"],
    ["ffV5k5-19S147-vkkV1F", "リザードンex"],
    ["LQggLn-hXlwFo-9nggHn", "ミライドンex"],
    ["HNnQHg-Ei40nZ-nnHgPn", "テツノカイナex"],
    ["xD8cKc-k7heaT-4YccD8", "ゲッコウガex"],
    ["N6QHQQ-GQ3mVh-nLHLgL", "テツノイバラex"],
    ["Y4D8Kc-mGCdwQ-4x84cc", "タケルライコex"],
    ["88c44Y-xebFYh-84cYDK", "ドラパルトex"],
    ["Q9gnNL-vKRd1M-gHgnLN", "タケルライコex オーガポン"],
    ["FdVk5k-BGnlAc-Fvb5k5", "ロスト"],
    ["9nQHin-84ADW9-ngn9gg", "ミライドンex"],
    ["9gHLgg-2wVkEH-9nHNiL", "カビゴン"],
    ["gnnLgg-W6C7eI-nL9H6g", "サーナイトex"],
    ["Syy2pM-XedU2X-yRpEXS", "オリジンディアルガ"]
  ]


  module_function
  def guess(world, deck)
    cos, name = Known.map {|known|
      [world.cos(known.first, deck).clamp(0,1.0), known.last]
    }.max
    pp [cos, deck, name] if cos < 0.9
    name
  end
end

if __FILE__ == $0
  pp DeckName::Known.sort_by {|x| x.last}
end